volumes:
  sqldb-data:

services:
  frontend:
    build:
      context: ./DockerCourseFrontend/DockerCourseFrontend/.
      dockerfile: Dockerfile
    image: 0399552503/frontend
    container_name: frontend
    ports:
      - "1234:80"

  api:
    build:
      context: ./DockerCourseAPI/.
      dockerfile: DockerCourseAPI/Dockerfile
    image: 0399552503/api
    container_name: api
    ports:
      - "17860:80"

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Dometrain#123
    ports:
      - "1433:1433"
    volumes:
      - sqldb-data:/var/opt/mssql

  database-seed:
    depends_on: [database]
    build:
      context: Database/
      dockerfile: Dockerfile
    container_name: database-seed
